In [1]:
# Dependencies and Setup
import pandas as pd

In [2]:
#read in data from csv
filepath = 'resources/city_weather.csv'
data = pd.read_csv(filepath)

In [3]:
# create new dataframe with only the parameters of interest
data_df = pd.DataFrame(data[['city','lat','main_temp','cloudiness','humidity','wind_speed']])
data_df

                  city    lat  main_temp  cloudiness  humidity  wind_speed
0                Bluff -23.58        NaN         0.0      11.0       11.68
1               Castro -42.48        NaN        97.0      94.0        2.89
2            Busselton -33.64        NaN         0.0      52.0        8.95
3               Kodiak  39.95      27.39         1.0      42.0        1.99
4           Irbeyskoye  55.64        NaN        76.0      67.0        5.35
5               Barrow -38.31        NaN         2.0      91.0        6.91
6             Hamilton  43.26      29.79        75.0      92.0        4.70
7            Jamestown -33.21        NaN        57.0      36.0       22.77
8               Tiznit  29.70        NaN         3.0      45.0        0.43
9             Pochutla  15.74      82.74        40.0      74.0        7.70
10        Kudahuvadhoo   2.67        NaN        89.0      76.0       12.17
11             Rikitea -23.12        NaN        93.0      85.0       13.06
12            Cherskiy  68.75        NaN       100.0      75.0        8.10
13             Qaanaaq  77.48        NaN         0.0      67.0        7.27
14          Kaitangata -46.28        NaN        62.0      73.0       18.48
15        Punta Arenas -53.16        NaN        98.0      81.0       13.31
16          Diamantino -14.40        NaN        99.0      95.0        5.77
17            Hermanus -34.42        NaN         5.0      81.0       11.30
18     Bambous Virieux -20.34      75.20        40.0      78.0       12.75
19             Margate -43.03      48.20        40.0      70.0        8.05
20        Independenta  45.48        NaN       100.0      73.0        6.15
21            San Juan -31.54        NaN         0.0      25.0        5.44
22                Hovd  63.83      18.97         0.0      85.0        3.36
23                Lebu   8.96      55.40        40.0      62.0        3.36
24            Floriano  -6.77        NaN        72.0      41.0        4.45
25         Tuktoyaktuk  69.44      14.00        90.0      72.0       19.46
26            Sertania  -8.07        NaN       100.0      86.0        7.52
27      Saint-Philippe  45.36      29.19        90.0      62.0        6.33
28           Caravelas -17.73        NaN         0.0      94.0        5.70
29           Beni Suef  29.07        NaN         0.0      79.0        4.56
...                ...    ...        ...         ...       ...         ...
1401      Buenos Aires -34.61      61.99        40.0      67.0       16.11
1402             Kuito -12.38        NaN       100.0      95.0        5.68
1403            Devrek  41.22        NaN        36.0      53.0        5.55
1404         Henderson  36.04      72.18         1.0      17.0        5.82
1405        Kosh-Agach  49.99        NaN        50.0      62.0        2.35
1406     Middle Island  40.88      45.59        90.0      81.0       13.87
1407          Tateyama  36.66      53.60        75.0      58.0        9.17
1408           Le Port  42.87        NaN        80.0      91.0        5.59
1409  Fort Myers Beach  26.45      76.96         1.0      74.0        4.70
1410        Toora-Khem  52.47        NaN        79.0      84.0        1.86
1411            Garowe   8.41        NaN        39.0      81.0        8.43
1412           Huadian  42.97        NaN         0.0      35.0        9.35
1413  Glenwood Springs  39.55      36.57         1.0      42.0        8.05
1414             Terme  41.21      50.00        26.0      87.0        4.70
1415           Kendari  -3.99        NaN        49.0      36.0        3.89
1416         Lexington  38.05      35.64        90.0      86.0        6.93
1417            Riyadh  24.63      73.40        87.0      31.0        4.70
1418           Fremont  37.55      56.80         1.0      81.0        5.82
1419         Boyolangu  -8.09        NaN         3.0      47.0        8.79
1420           Warmbad  50.67        NaN       100.0      81.0        2.24
1421          Shirokiy  53.87        NaN       100.0      97.0        2.08
1422         Pokosnoye  55.53        NaN        99.0      78.0        8.37
1423           Wyndham  51.61      40.60        90.0      93.0       10.29
1424            Abeche  13.83        NaN         0.0      15.0       18.41
1425         Marystown  47.17        NaN       100.0      69.0       20.13
1426            Wukari   7.87        NaN       100.0      75.0        2.28
1427             Dubti  11.74        NaN         0.0      42.0        4.41
1428            Koumac -20.56        NaN        33.0      54.0        4.94
1429        Springdale  36.19      33.21         1.0      74.0        6.93
1430           Turlock  37.49      67.78         1.0      52.0        5.08

[1431 rows x 6 columns]

In [10]:
data_df.to_html('data_html.html')